### PR TITLE
upgrade Core to v0.15.xx

### PR DESCRIPTION
**Pull request by jvillard**
Is this something you wouldn't mind merging? I was playing with tdigest in infer and needed a more recent version of Core.

Tested that `dune build @all` and `dune runtest` are both happy.

### CODE REVIEW

**Comment by SGrondin** [comment]
Thank you! It will be released as `tdigest` `2.0.0`

**Comment by SGrondin** [comment]
@jvillard [this](https://github.com/facebook/infer/blob/61801a371bd6b3a6c666ae136e66c1b66cebe52e/infer/src/base/Timings.ml) is really neat. I'll add an `is_empty` function for you. It will be a lot more efficient than
```ocaml
(Tdigest.info digest).count > 0
```

**Comment by jvillard** [comment]
Thanks @SGrondin! And thanks for the great library :)

**Comment by SGrondin** [comment]
@jvillard version [2.1.1](https://github.com/SGrondin/tdigest/releases/tag/2.1.1) adds `Tdigest.is_empty` as well as efficient `sexp_of_t`/`t_of_sexp` (using `to_string`/`of_string` under the hood)

**Pull request merged**
